// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChangePrice.Data.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChangePrice.Data.DataBase.Configurations
{
    public partial class AlertConfiguration : IEntityTypeConfiguration<Alert>
    {
        public void Configure(EntityTypeBuilder<Alert> entity)
        {
            entity.Property(e => e.AlertId).HasColumnName("AlertID");

            entity.Property(e => e.DateRegisterTime).HasColumnType("datetime");

            entity.Property(e => e.Description).HasMaxLength(500);

            entity.Property(e => e.LastTouchPrice).HasColumnType("datetime");

            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("price");

            entity.Property(e => e.PriceDifference).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.UserId)
                .HasMaxLength(450)
                .HasColumnName("UserID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Alert> entity);
    }
}
