// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChangePrice.Data.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChangePrice.Data.DataBase.Configurations
{
    public partial class CandleConfiguration : IEntityTypeConfiguration<Candle>
    {
        public void Configure(EntityTypeBuilder<Candle> entity)
        {
            entity.Property(e => e.CandleId).HasColumnName("CandleID");

            entity.Property(e => e.ClosePrice).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.HighPrice).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.LowPrice).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.OpenPrice).HasColumnType("decimal(18, 0)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Candle> entity);
    }
}
