// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChangePrice.Data.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ChangePrice.Data.DataBase.Configurations
{
    public partial class UserNameConfiguration : IEntityTypeConfiguration<UserName>
    {
        public void Configure(EntityTypeBuilder<UserName> entity)
        {
            entity.HasKey(e => e.UserId)
                .HasName("PK__UserName__1788CCAC1FDDD4C7");

            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.Property(e => e.EmailAddress).HasMaxLength(500);

            entity.Property(e => e.Name).HasMaxLength(120);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserName> entity);
    }
}
