// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChangePrice.Data.DataBase.Configurations;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace ChangePrice.Data.DataBase
{
    public partial class CryptoDbContext : IdentityDbContext
    {
        public CryptoDbContext()
        {
        }

        public CryptoDbContext(DbContextOptions<CryptoDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Alert> Alert { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.AlertConfiguration());

            OnModelCreatingPartial(modelBuilder);
            base.OnModelCreating(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
